apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  - level: RequestResponse
    resources:
    - group: "cluster.x-k8s.io"
      resources:
      - clusters
      - machinedeployments
    - group: "infrastructure.giantswarm.io"
      resources:
      - awsclusters
      - awsmachinedeployments
      - g8scontrolplanes
      - awscontrolplanes
  # A catch-all rule to log all other requests at the Metadata level.
  - level: Metadata
    # Long-running requests like watches that fall under this rule will not
    # generate an audit event in RequestReceived.
    omitStages:
      - "RequestReceived"
